patreon: AahhsSjsj
custom:
  [
    "https://github.com/AahhsSjsj/Bot-Tutoriales-V13",
    "https://github.com/AahhsSjsj/Bot-Tutoriales-V12",
    "https://github.com/AahhsSjsj/Bot-Tutoriales-V13/tree/readmes",
    "https://github.com/AahhsSjsj/Bot-Tutoriales-V12/tree/readmes",
  ]
